# Site setings
name: 'Ottawa Birth Science'
description: 'Doula support for families in and around the Ottawa area.'
meta_description: 'Evidence-based doula care for families in and around Ottawa ON'
logo: 'BScLogoWeb.svg'
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image:
  greetings: "Welcome to Birth Science, where we are passionate about providing compassionate, evidence-based doula care and education to all types of families in and around Ottawa, Ontario.
"
favicon:
baseurl:
production_url: https://royce.netlify.com/
disqus:
mailchimp_url:
# Add your GA Tracking Id
ga_analytics:

# Contact form setings
email: danielle.mceachern@gmail.com
contact_page_description: "Get in touch to arrange a complimentary consultation, and learn how compassionate doula support can uplift your birth and postpartum experience."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
#twitter:
#facebook:
#github:
#codepen:
#dribbble:
#medium:
instagram: 'birth.science'
#pinterest:
#linkedin:
#producthunt:
#quora:

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Birth
    url: /birth
  - text: Postpartum
    url: /postpartum
#  - text: Prenatal Education
#    url: /education
  - text: Abortion
    url: /abortion
#  - text: FAQs
#    url: /FAQ
#  - text: Resources
#    url: /resources
#  - text: Testimonials
#    url: /testimonials
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap


# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
